/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LogoutButton: typeof import('./src/components/auth/LogoutButton.vue')['default']
    MatrizCard: typeof import('./src/components/matriz/MatrizCard.vue')['default']
    MatrizDimensionInput: typeof import('./src/components/matriz/MatrizDimensionInput.vue')['default']
    MatrizInput: typeof import('./src/components/matriz/MatrizInput.vue')['default']
    MatrizResults: typeof import('./src/components/matriz/MatrizResults.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
