version: '2.24'

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    env_file: ./.env
    environment:
      - $VITE_BASE_URL=$VITE_BASE_URL
    ports:
      - 8080:8080